concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "c# build test deploy"
  url = "http://host.docker.internal"
  id = 4
  token = "glrtr-L-32VjtPCdn4POgN6KWRVG86MQpwOjIKdDozCw.01.1213g669i"
  token_obtained_at = 2025-06-16T14:54:48Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "mcr.microsoft.com/dotnet/sdk:7.0"
    privileged = true  # pour la build de l image docker
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
